### ISSUE TITLE
Console Messages

### ISSUE THREAD

**Issue by josephgupkim** [Artifex-Latronis/Expresso#7]
Although the messages in the console don't really affect the functionality of your project: I would recommend to go ahead and try giving the children unique IDs to get rid of the console message and review the importance in doing so.

**Comment by Artifex-Latronis** [comment]
Can you elaborate a little more on what you mean by children and unique IDs? I am not following.

**Comment by josephgupkim** [comment]
Check your console messages and/or read this:
https://github.com/facebook/react/issues/1342

**Comment by Artifex-Latronis** [comment]
The console messages were used to help show me what was being passed by the test program to populate the req object (and they only run in DEV mode). I wanted to make sure I understood what was being passed for each individual route. Are you saying that these outputs should have unique ID's? You reference "getting rid of the console message" and I don't understand how else I would see what is being passed to me without outputting it into the console. Is there something I am missing?

**Comment by Artifex-Latronis** [comment]
Ok, you are referencing the console on the webpage itself. I have not spent much time there. I will check it out. Thanks.
